queues:
  repairQueue:
    id: repairQueue
    services: phoneRepair
    servicers: 2
    tts: 15
  paymentQueue:
    id: paymentQueue
    services: phonePayments, communalPayments
    servicers: 5
    tts: 1

